export const SETERR = 'SETERR'
export const SETERROR = 'SETERROR'
export const GETGLBERR = 'GETGLBERR'
export const SETCONFMENU = 'SETCONFMENU'
export const SETADDCOUNT = 'SETADDCOUNT'
export const SETBLETOGGLED = 'SETBLETOGGLED'
export const SETJPUSHDATA = 'SETJPUSHDATA'
export const SETFEATHERS = 'SETFEATHERS'


